{% set name = "s1proc" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  #noarch: python
  entry_points:
    - s1proc = s1proc.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy >=1.23
    - pandas >=2.0
    - numba >=0.58
    - requests >=2.31
    - matplotlib >=3.8
    - tyro >=0.9
    - tqdm >=4
    - libtiff
    - sqlite

test:
  imports:
    - s1proc

  commands:
    - python -c "import s1proc; print('import ok')"

about:
  home: "https://github.com/WWSAR/sentinel_gpu_processor"
  license: MIT
  summary: "GPU-accelerated Sentinel-1 SAR processing tools"

extra:
  recipe-maintainers:
    - Ke Wang