context:
  name: "s1proc"
  version: "0.1.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: .

build:
  number: 0
  script:
    - if: win
      then:
        - bld.bat
    - if: unix
      then:
        - build.sh
  python:
    entry_points:
      - s1proc = s1proc.cli:main

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
    - cuda-nvcc 12.4.*
    - cuda-cudart 12.4.*
    - cuda-cudart-dev 12.4.*
    - if: unix
      then: cuda-cudart-static 12.4.*
    - libcufft-dev >=11.0,<12
    - if: unix
      then: libcufft-static >=11.0,<12
  host:
    - python
    - pip
    - setuptools
    - libtiff
    - sqlite
    - cuda-cudart 12.4.*
    - cuda-cudart-dev 12.4.*
    - if: unix
      then: cuda-cudart-static 12.4.*
    - libcufft-dev >=11.0,<12
    - if: unix
      then: libcufft-static >=11.0,<12
  run:
    - python
    - cuda-cudart 12.4.*
    - libcufft >=11.0,<12
    - sqlite
    - libtiff
    - numpy >=1.23
    - pandas >=2.0
    - numba >=0.58
    - requests >=2.31
    - matplotlib >=3.8
    - tyro >=0.9
    - tqdm >=4
    - pyaps3 >=0.3.7
    - sentineleof >=0.12.0
    - sardem >=0.13.0
    - zarr >=2.18.3
    - dacite >=1.9.2

tests:
  - script:
      - python -c "import s1proc; print('import ok')"
