# I/O paths
io:
    data_path: data                       # zip files
    eof_path: eof                         # eof files
    proc_path: proc                       # intermediate outpus
    slc_path: slc                         # geocoded SLC
    ifg_path: igrams                      # raw wrapped interferograms
    amp_path: amp                         # multilooked amplitude 
    unw_path: unw                         # unwrapped interferograms
    time_series_path: analysis            # time series results
    dem_file: elevation.dem               # DEM grid
    rsc_file: elevation.dem.rsc           # rsc description file
    img_pair_file: subswath_list          # list of interferograms to process
    geometry_path: geometry               # geometry-related files (los/inc)
    ifg_corr_path: ifg_corrected          # corrected wrapped interferograms
    unw_corr_path: unw_corrected          # corrected unwrapped interferograms
    multilook_dem_file: dem/multilook.dem # multilooked DEM
    multilook_rsc_file: dem/multilook.rsc # multilooked rsc file
    mask_file: dem/mask.bin               # mask file (1: valid pixel, 0: invalid pixel)

# SLC and interferogram generation parameters
proc:
    download_dem: true  # automatic DEM downloading
    download_data: true # automatic Sentinel-1 data downloading
    download_eof: true # automatic precise orbit data downloading
    rowlook: 10
    collook: 20
    wavelength: 0.055465763
    min_tbl: 6       # minimum temporal baseline
    max_tbl: 360     # maximum temporal baseline
    min_sbl: 0       # minimum spatial baseline
    max_sbl: 300     # maximum spatial baseline
    ngpu:            # number of gpus used for parallel interferogram generation
    task_per_gpu:    # number of tasks running on each GPU

# Wrapped interferogram processing
# Interferogram filtering, for the moment, only Goldstein filter is implemented
filter:
    enable: false
    method: "goldstein"
    parameters:
        window_size: 32
        goldstein_alpha: 0.5

# Tropospheric delay correction, for the moment, era5 is the only allowed option
tropo:
    enable: true
    method: "era5"
    parameters:
        delay_path: "tropo_delay" # projected tropospheric delay
        hour: null
        flip_sign: false

# Phase ramp removal
detrend:
    enable: false
    type: "plane"       # plane or quadratic

# Phase unwrapping
unwrap:
    method: "whirlwind" # select between [whirlwind (recommended) and snaphu]
    parameters:
        only_save_phase: true
        # whirlwind parameters
        conncomp: false
        bridge: false
        # snaphu parameters
        cost_mode: "smooth" # select from [smooth, topo, defo]
        rowtile: null
        coltile: null
        rowoverlap: 200
        coloverlap: 200
        tile_nproc: null

# Time series
timeseries:
    method: "stack"
    parameters:
        ref_lon:
        ref_lat:
        # optional, default value = 4.0
        mad_scalar: 4
        threshold_sigma:
        periods:
            - ["20141101", "20170131"]
            - ["20141101", "20180131"]
            - ["20141101", "20190131"]
        check_points: false
        check_point_list: "checkpoints.txt"

# date and study area
date:
    start:
    end:
area:
    # [west, south, east, north]
    bbox:
    # [Descending, Ascending, null]
    flight_direction:
    # path_list is only used in the main configuration
    # users can remove paths that they do not want to process
    path_list:
    # users can remove frames that they do not want to process
    path_number:
    frame_list:
