#!/usr/bin/env python3
from __future__ import annotations

import glob
import os
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Sequence, Tuple

import numpy as np
from numpy.typing import NDArray

if TYPE_CHECKING:
    import dask.array as da

from s1proc import geocoordinates, sario
from s1proc._config import TroposphericParams
from s1proc._log import set_logging_level, setup_logger
from s1proc.utils import IfgList, get_files, los, multilook_dem

logger = setup_logger(name=__name__, level="INFO")


def read_orbit(orbfile: Path | str) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """read an orbit file generated by the Sentinel-1 processor

    Args:
        orbfile (str): orbit file

    Returns:
        tt (1d numpy array): time vector
        xx (2d numpy array): position vector
        vv (2d numpy array): velocity vector
    """
    with open(orbfile, "r") as f:
        line = f.readline()
        line = line.strip()
        try:
            # skip the first three line for old Sentinel-1 processor
            if np.abs(float(line) - int(line)) > 1e-10:
                for i in range(3):
                    line = f.readline()
        except Exception as e:
            print(e)
            line = f.readline()
            for i in range(3):
                line = f.readline()
        nstatvec = int(line.strip())
        tt = np.zeros(nstatvec)
        xx = np.zeros((nstatvec, 3))
        vv = np.zeros((nstatvec, 3))
        for i in range(nstatvec):
            line = f.readline()
            words = line.split()
            tt[i] = float(words[0])
            xx[i, 0] = float(words[1])
            xx[i, 1] = float(words[2])
            xx[i, 2] = float(words[3])
            vv[i, 0] = float(words[4])
            vv[i, 1] = float(words[5])
            vv[i, 2] = float(words[6])
    return tt, xx, vv


def download_era5(
    date_list: Sequence[Path | str],
    hour: int,
    output_path: Path | str,
    rsc_file: Path | str,
):
    """
    Download tropospheric delay files

    Parameters
    ----------
    date_list: Sequence[Path|str]
        A list of dates to process
    hour: int
        The hour of SAR data acquisition
    output_path: Path|str
        Output directory of tropospheric delay files
    rsc_file: Path|str
        An rsc file specifying the data coverage
    """
    import pyaps3 as pa

    os.makedirs(output_path, exist_ok=True)
    rsc = geocoordinates.GeoCoordinates(rsc_file)
    # south, north, west, east boundary of the study area
    snwe = [
        np.floor(rsc.latmin),
        np.ceil(rsc.latmax),
        np.floor(rsc.lonmin),
        np.ceil(rsc.lonmax),
    ]
    snwe = [int(x) for x in snwe]

    def snwe_to_string(snwe):
        s, n, w, e = snwe
        area = ""
        area += "_S{}".format(abs(s)) if s < 0 else "_N{}".format(abs(s))
        area += "_S{}".format(abs(n)) if n < 0 else "_N{}".format(abs(n))
        area += "_W{}".format(abs(w)) if w < 0 else "_E{}".format(abs(w))
        area += "_W{}".format(abs(e)) if e < 0 else "_E{}".format(abs(e))
        return area

    area = snwe_to_string(snwe)
    grb_files = [
        os.path.join(output_path, f"ERA5{area}_{d}_{hour}.grb") for d in date_list
    ]
    download_date_list = []
    for d, grb_file in zip(date_list, grb_files):
        if not os.path.exists(grb_file):
            download_date_list.append(d)
    if len(download_date_list) == 0:
        logger.debug("All grb files exist, nothing to download")
        return
    pa.ECMWFdload(date_list, hr=hour, filedir=output_path, model="ERA5", snwe=snwe)


def tropo_proj_era5(
    input_files: Sequence[Path | str],
    lat: np.ndarray,
    lon: np.ndarray,
    dem: np.ndarray,
    inc: np.ndarray,
    output_path: Path | str,
    verbose: bool = False,
):
    """
    project tropospheric delay on the grid defined by lat/lon/dem

    Parameters
    ----------
    input_files: Sequence[Path|str]
        Input grb files
    lat: 2d numpy array (nrow x ncol)
        latitude of grid points
    lon: 2d numpy array (nrow x nocl)
        longitude of grid points
    dem: 2d numpy array (nrow x ncol)
        elevation (above WGS84 ellipsoid) of grid points
    inc: 2d numpy array (nrow x ncol)
        local incidence angle (in degree)
    output_path: Path
        where to store the projected tropospheric delay product

    Notes
    -------
    A projected tropsheric delay product will be created for each SAR
    acquisition date and save as {output_path}/{date}.delay (nrow x ncol in
    float32 format). Note that the unit of tropospheric delay is meter.
    """
    import pyaps3 as pa

    logger.info("calculate tropospheric delay from GRB files...")
    os.makedirs(output_path, exist_ok=True)
    for grb_file in input_files:
        basename = os.path.basename(grb_file)
        date = str(basename).split("_")[-2]
        output_file = os.path.join(output_path, f"{date}.delay")
        if os.path.exists(output_file):
            continue
        obj = pa.PyAPS(
            grb_file, dem=dem, inc=inc, lat=lat, lon=lon, grib="ERA5", verb=verbose
        )
        phs = obj.getdelay()
        phs.astype(np.float32).tofile(output_file)
        if verbose:
            logger.info(f"Save projected tropospheric delay to {output_file}")


def _era5_correction(
    input_file: Path | str,
    output_file: Path | str,
    nrow: int,
    ncol: int,
    tropo_params: TroposphericParams,
    wvl=0.055465763,
):
    """
    Perform tropospheric noise correction

    Parameters
    ----------
    input_file: Path|str
        Interferogram to be corrected
    nrow: int
        number of rows of the image
    ncol: int
        number of columns of the image
    tropo_params: TroposphericParams
        Parameters for tropospheric delay correction
    wvl: float
        Wavelength in meter

    Notes
    -------
    This function calulates the differential tropospheric delay between the
    secondary date and the reference date of the interferogram, performs the
    tropospheric noise correction.
    """
    basename = os.path.basename(input_file)
    date1 = basename[0:8]
    date2 = basename[9:17]
    delay_file1 = os.path.join(tropo_params.delay_path, f"{date1}.delay")
    delay_file2 = os.path.join(tropo_params.delay_path, f"{date2}.delay")
    delay1 = np.fromfile(delay_file1, dtype=np.float32)
    delay2 = np.fromfile(delay_file2, dtype=np.float32)
    aps = (delay1 - delay2) / wvl * 4 * np.pi
    aps = np.reshape(aps, (nrow, ncol))
    if basename[-4:] == ".int":
        ifg = sario.readslc(input_file, ncol)
        if tropo_params.flip_sign:
            ifgcorr = ifg * np.exp(1j * aps)
        else:
            ifgcorr = ifg * np.exp(-1j * aps)
        sario.saveslc(ifgcorr, output_file)
    else:
        ifg = sario.readc(input_file, ncol)
        if tropo_params.flip_sign:
            ifg = ifg.real + 1j * (ifg.imag + aps)
        else:
            ifg = ifg.real + 1j * (ifg.imag - aps)
        sario.savec(ifgcorr, output_file)


def _tropo_block(
    ifg_block: NDArray[np.complex64],
    delay_block: NDArray[np.float32],
    ref_idx: NDArray[np.int32],
    sec_idx: NDArray[np.int32],
    wvl: float,
    flip_sign: bool,
    block_info: list[dict] | None = None,
) -> NDArray[np.complex64]:
    """Per-chunk kernel for :func:`batch_tropo_correction`.

    Each call receives **one** interferogram block (axis-2 size = 1) and
    the full delay stack for the same spatial extent.  The interferogram
    index is read from *block_info* so that only the two relevant delay
    slices are selected from *delay_block*, keeping the per-chunk working
    set as small as possible.

    Parameters
    ----------
    ifg_block : ndarray, shape ``(row_chunk, ncol, 1)``
        One interferogram, ``complex64``.
    delay_block : ndarray, shape ``(row_chunk, ncol, ndate)``
        All projected delays for this spatial block, ``float32``.
    ref_idx : ndarray of int32, shape ``(nifg,)``
    sec_idx : ndarray of int32, shape ``(nifg,)``
    wvl : float
    flip_sign : bool
    block_info : list[dict] | None
        Dask block metadata; ``block_info[0]['chunk-location'][2]``
        gives the interferogram index.
    """
    if block_info is not None:
        k = block_info[0]["chunk-location"][2]
    else:
        k = 0  # direct call fallback
    r = int(ref_idx[k])
    s = int(sec_idx[k])
    aps = (delay_block[:, :, r] - delay_block[:, :, s]) * (4.0 * np.pi / wvl)
    sign = 1j if flip_sign else -1j
    return ifg_block[:, :, 0:1] * np.exp(sign * aps)[:, :, None]


def batch_tropo_correction(
    ifg_files: Sequence[str | Path],
    delay_path: str | Path,
    nrow: int,
    ncol: int,
    wvl: float = 0.055465763,
    flip_sign: bool = False,
    row_chunk: int | None = None,
) -> "da.Array":
    """Apply tropospheric phase correction to a stack of wrapped interferograms.

    Interferograms and projected tropospheric delay maps are loaded as
    virtual zarr arrays via :func:`sario.create_virtual_stack` (zero-copy).
    The correction is applied with :func:`dask.array.map_blocks` so that
    only one interferogram and the delay-date axis for one spatial block
    are held in memory at any time.

    Parameters
    ----------
    ifg_files : Sequence[str | Path]
        Paths to wrapped interferograms (flat binary ``complex64``,
        row-major).  Filenames must follow the ``YYYYMMDD_YYYYMMDD.int``
        convention.
    delay_path : str | Path
        Directory containing per-date projected delay files named
        ``{YYYYMMDD}.delay`` (flat binary ``float32``, row-major,
        ``(nrow, ncol)`` elements).
    nrow : int
        Number of image rows.
    ncol : int
        Number of image columns.
    wvl : float
        Radar wavelength in metres (Sentinel-1 default: ~0.0555 m).
    flip_sign : bool
        If True, apply the correction with sign ``+j * APS`` instead of
        ``-j * APS``.
    row_chunk : int | None
        Rows per chunk in the virtual stacks.  When ``None``, defaults
        to *nrow* (one chunk per image).

    Returns
    -------
    da.Array
        Lazy 3-D dask array of corrected wrapped interferograms with
        shape ``(nrow, ncol, nifg)`` and dtype ``complex64``.

    Raises
    ------
    FileNotFoundError
        If any required delay file is missing.  All delay files are
        checked eagerly before lazy computation begins.
    """
    import dask.array as da

    from s1proc.sario import create_virtual_stack

    delay_path = Path(delay_path)

    # -- Resolve IFG → date pairs ----------------------------------------------
    ifg_list = IfgList([str(p) for p in ifg_files])
    ref_indices, sec_indices = ifg_list.ref_sec_indices()
    nifg = ifg_list.nifg
    ndate = ifg_list.ndate
    dates = list(ifg_list.dates)

    if row_chunk is None:
        row_chunk = nrow

    logger.info(
        "Batch tropo correction (map_blocks): %d ifgs, %d dates, "
        "shape=(%d, %d), ifg_chunk=(%d, %d, 1)",
        nifg,
        ndate,
        nrow,
        ncol,
        row_chunk,
        ncol,
    )

    # -- Check all delay files exist before building the lazy graph ------------
    delay_files: list[Path] = []
    for d in dates:
        df = delay_path / f"{d}.delay"
        if not df.exists():
            raise FileNotFoundError(
                f"Delay file {df} is missing. Run tropo_preproc first."
            )
        delay_files.append(df)

    # -- Virtual stacks (zero-copy) --------------------------------------------
    # Interferogram stack: chunked (row_chunk, ncol, 1) — one ifg per chunk
    ifg_mapper = create_virtual_stack(
        [Path(p) for p in ifg_files],
        np.complex64,
        nrow,
        ncol,
        row_chunk,
        new_axis=2,
    )
    ifg_stack = da.from_zarr(ifg_mapper)
    ifg_stack = ifg_stack.rechunk({0: row_chunk, 1: ncol, 2: 1})

    # Delay stack: chunked (row_chunk, ncol, -1) — all dates, one block
    delay_mapper = create_virtual_stack(
        delay_files,
        np.float32,
        nrow,
        ncol,
        row_chunk,
        new_axis=2,
    )
    delay_stack = da.from_zarr(delay_mapper)
    delay_stack = delay_stack.rechunk({0: row_chunk, 1: ncol, 2: -1})

    # -- map_blocks ------------------------------------------------------------
    # Dask broadcasts the single axis-2 block of `delay_stack` against the
    # `nifg` axis-2 blocks of `ifg_stack`.  Each call to `_tropo_block`
    # therefore receives:
    #   ifg_block  : (row_chunk, ncol, 1)      complex64
    #   delay_block: (row_chunk, ncol, ndate)  float32
    # Peak memory per task is ~ row_chunk × ncol × (8 + 4·ndate + 12) bytes.
    corrected = da.map_blocks(
        _tropo_block,
        ifg_stack,
        delay_stack,
        dtype=np.complex64,
        chunks=ifg_stack.chunks,
        ref_idx=ref_indices,
        sec_idx=sec_indices,
        wvl=wvl,
        flip_sign=flip_sign,
    )

    logger.info(
        "Batch tropo correction graph built (map_blocks): %d ifgs, "
        "lazy result dtype=%s",
        nifg,
        corrected.dtype,
    )
    return corrected


def tropo_proj(
    dem_file: Path | str,
    rsc_file: Path | str,
    look_angle_file: Path | str,
    /,
    tropo_delay_path: Path | str = "tropo_delay",
    verbose: bool = False,
):
    """
    Download tropospheric delay data and do projection

    Parameters
    ----------
    dem_file: Path|str
        DEM file
    rsc_file: Path|str
        rsc file
    look_angle_file: Path|str
        Look angle at each radar pixel
    tropo_delay_path: path|str
        Directory to store tropospheric delay product
    verbose: bool
        Show processing message
    """
    os.makedirs(tropo_delay_path, exist_ok=True)
    grb_path = Path(os.path.join(tropo_delay_path, "grb"))
    if not grb_path.is_dir():
        logger.error("Cannot find the folder containting grb files")
        exit(1)

    # read lat/lon/dem/inc
    logger.info("project tropospheric delay to LOS directions")
    rsc = geocoordinates.GeoCoordinates(rsc_file)
    nrow, ncol = rsc.nlat, rsc.nlon
    lat, lon = rsc.grid()
    dem = np.fromfile(dem_file, dtype=np.int16).reshape(nrow, ncol)
    inc = np.fromfile(look_angle_file, dtype=np.float32).reshape(nrow, ncol)
    grb_files = glob.glob(os.path.join(grb_path, "*.grb"))
    tropo_proj_era5(grb_files, lat, lon, dem, inc, tropo_delay_path, verbose=verbose)


def tropo_preproc(
    ifg_path: str | None = None, config: str = "config.yaml", verbose: bool = False
):
    """
    Run tropospheric noise correction

    Parameters
    ----------
    ifg_path: str
        Interferograms to be corrected
    config: Path|str
        Configuration file
    verbose: bool
        If True, set the logging level to DEBUG
    """
    if verbose:
        set_logging_level(logger, "DEBUG")
    from s1proc._config import load_config

    cfg = load_config(config)
    icfg = cfg.io
    pcfg = cfg.proc
    tcfg = cfg.tropo

    # determine the acquisition hour
    if tcfg.parameters.hour is None:
        zip_list_file = os.path.join(icfg.data_path, "zip_list")
        zip_file = None
        if not os.path.exists(zip_list_file):
            zip_list = glob.glob(os.path.join(icfg.data_path, "*.zip"))
            if len(zip_list) > 0:
                zip_file = zip_list[0]
            with open(zip_list_file, "w") as f:
                f.write("\n".join(zip_list))
        else:
            with open(zip_list_file, "r") as f:
                zip_file = f.readline().strip()
        if zip_file is None or zip_file == "":
            logger.error(
                "Cannot derive the acquisition hour of radar data. "
                + "User must specify the hour option in the configuration "
                + "file."
            )
            return
        else:
            sent = sario.sentinel_parser(zip_file)
            start_time = datetime.strptime(sent["start_time"], "%Y%m%dT%H%M%S")
            hour = start_time.hour
    else:
        hour = tcfg.parameters.hour
    logger.debug(f"Acquisition hour is set to {hour}")

    # parse input data
    if ifg_path is None:
        ifg_path = icfg.ifg_path
    raw_ifg_list = get_files(ifg_path, "int")
    ifg_list = IfgList(raw_ifg_list)
    date_list = ifg_list.get_date_list()

    # download files for tropospheric noise correction
    tropo_delay_path = tcfg.parameters.delay_path
    grb_path = os.path.join(tropo_delay_path, "grb")
    os.makedirs(grb_path, exist_ok=True)
    logger.info("download files for tropspheric noise correction")
    download_era5(date_list, hour, grb_path, icfg.rsc_file)

    # Project tropospheric delay to imaging grid
    dem_file = icfg.multilook_dem_file
    rsc_file = icfg.multilook_rsc_file
    geometry_path = icfg.geometry_path
    if not os.path.exists(geometry_path):
        os.makedirs(geometry_path)
    losvec_file = os.path.join(geometry_path, "los")
    look_angle_file = os.path.join(geometry_path, "look_angle")
    if not os.path.exists(dem_file) or not os.path.exists(rsc_file):
        multilook_dem(
            icfg.dem_file, icfg.rsc_file, dem_file, rsc_file, pcfg.rowlook, pcfg.collook
        )
    if not os.path.exists(look_angle_file):
        los(dem_file, rsc_file, icfg.proc_path, losvec_file, look_angle_file)
    tropo_proj(dem_file, rsc_file, look_angle_file, tropo_delay_path, verbose)
