#!/usr/bin/env python3
from __future__ import annotations

import glob
import numpy as np
import os
from datetime import datetime
from matplotlib import pyplot as plt
from pathlib import Path
from tqdm import tqdm
from typing import Sequence, Tuple
plt.rcParams['image.interpolation'] = 'none'

from s1proc import geocoordinates
from s1proc import orbit
from s1proc import sario
from s1proc.utils import multilook_dem, los, IfgList
from s1proc._log import setup_logger, set_logging_level
logger = setup_logger(name = __name__, level = 'INFO')

def get_input_files(input_path:str) -> List[str]:
    """
    Get interferograms to be corrected

    Parameters
    ----------
    input_path: str
        Input path
    
    Returns
    -------
    ifg_list: List[str]
        A list of interferograms to prcoess
    """
    p = Path(input_path)
    if p.is_file():
        return [input_path]
    elif p.is_dir():
        int_list = glob.glob(os.path.join(input_path,'*.int'))
        unw_list = glob.glob(os.paht.join(input_path,'*.unw'))
        if len(int_list) > 0 and len(unw_list) > 0:
            logger.warning('Find both wrapped and unwrapped interferograms' +
                    f' in the input directory {input_path}.')
        ifg_list = np.concatenate(int_list, unw_list)
        if len(ifg_list) == 0:
            logger.warning('Cannot find any interferogram from the input ' +
                    f'directory {input_path}.')
    else:
        ifg_list = glob.glob(input_path)
        if len(ifg_list) == 0:
            logger.warning('Cannot find any interferogram from the input ' +
                    f'pattern {input_path}.')
    return ifg_list

def read_orbit(orbfile:Path|str)->Tuple[np.ndarray,np.ndarray,np.ndarray]:
    """read an orbit file generated by the Sentinel-1 processor

    Args:
        orbfile (str): orbit file

    Returns:
        tt (1d numpy array): time vector
        xx (2d numpy array): position vector
        vv (2d numpy array): velocity vector
    """
    with open(orbfile,"r") as f:
        line = f.readline()
        line = line.strip()
        try:
            # skip the first three line for old Sentinel-1 processor
            if np.abs(float(line)-int(line))>1e-10:
                for i in range(3):
                    line = f.readline()
        except Exception as e:
            print(e)
            line = f.readline()
            for i in range(3):
                line = f.readline()
        nstatvec = int(line.strip())
        tt = np.zeros(nstatvec)
        xx = np.zeros((nstatvec,3))
        vv = np.zeros((nstatvec,3))
        for i in range(nstatvec):
            line = f.readline()
            words = line.split()
            tt[i] = float(words[0])
            xx[i,0] = float(words[1])
            xx[i,1] = float(words[2])
            xx[i,2] = float(words[3])
            vv[i,0] = float(words[4])
            vv[i,1] = float(words[5])
            vv[i,2] = float(words[6])
    return tt,xx,vv

def download_era5(
        date_list: Sequence[Path|str],
        hour: int,
        output_path: Path|str,
        rsc_file: Path|str):
    """
    Download tropospheric delay files

    Parameters
    ----------
    date_list: Sequence[Path|str]
        A list of dates to process
    hour: int
        The hour of SAR data acquisition
    output_path: Path|str
        Output directory of tropospheric delay files
    rsc_file: Path|str
        An rsc file specifying the data coverage
    """
    import pyaps3 as pa
    os.makedirs(output_path,exist_ok=True)
    rsc = geocoordinates.GeoCoordinates(rsc_file)
    # south, north, west, east boundary of the study area
    snwe = [np.floor(rsc.latmin),np.ceil(rsc.latmax),
            np.floor(rsc.lonmin),np.ceil(rsc.lonmax)]
    snwe = [int(x) for x in snwe]
    def snwe_to_string(snwe):
        s, n, w, e = snwe
        area = ''
        area += '_S{}'.format(abs(s)) if s < 0 else '_N{}'.format(abs(s))
        area += '_S{}'.format(abs(n)) if n < 0 else '_N{}'.format(abs(n))
        area += '_W{}'.format(abs(w)) if w < 0 else '_E{}'.format(abs(w))
        area += '_W{}'.format(abs(e)) if e < 0 else '_E{}'.format(abs(e))
        return area
    area = snwe_to_string(snwe)
    grb_files = [os.path.join(output_path,
                 f'ERA5{area}_{d}_{hour}.grb') for d in date_list]
    download_date_list = []
    for d, grb_file in zip(date_list, grb_files):
        if not os.path.exists(grb_file):
            download_date_list.append(d)
    if len(download_date_list) == 0:
        logger.debug('All grb files exist, nothing to download')
        return
    pa.ECMWFdload(date_list, hr=hour, filedir=output_path,
                  model='ERA5', snwe=snwe)

def tropo_proj_era5(
        input_files: Sequence[Path|str],
        lat: np.ndarray,
        lon: np.ndarray,
        dem: np.ndarray,
        inc: np.ndarray,
        output_path: Path|str,
        verbose: bool = False):
    """
    project tropospheric delay on the grid defined by lat/lon/dem

    Parameters
    ----------
    input_files: Sequence[Path|str]
        Input grb files
    lat: 2d numpy array (nrow x ncol)
        latitude of grid points
    lon: 2d numpy array (nrow x nocl)
        longitude of grid points
    dem: 2d numpy array (nrow x ncol)
        elevation (above WGS84 ellipsoid) of grid points
    inc: 2d numpy array (nrow x ncol)
        local incidence angle (in degree)
    output_path: Path
        where to store the projected tropospheric delay product

    Notes
    -------
    A projected tropsheric delay product will be created for each SAR
    acquisition date and save as {output_path}/{date}.delay (nrow x ncol in
    float32 format). Note that the unit of tropospheric delay is meter.
    """
    import pyaps3 as pa
    logger.info('calculate tropospheric delay from GRB files...')
    os.makedirs(output_path, exist_ok=True)
    for grb_file in input_files:
        basename = os.path.basename(grb_file)
        date = str(basename).split('_')[-2]
        output_file = os.path.join(output_path,f'{date}.delay')
        if os.path.exists(output_file):
            continue
        obj = pa.PyAPS(grb_file, dem=dem, inc=inc, lat=lat, lon=lon,
                       grib='ERA5', verb=verbose)
        phs = obj.getdelay()
        phs.astype(np.float32).tofile(output_file)
        if verbose:
            logger.info(f'Save projected tropospheric delay to {output_file}')

def _era5_correction(
        input_files: Sequence[str],
        nrow:int,
        ncol:int,
        wvl = 0.055465763,
        delay_path: Path|str = 'tropo',
        output_path: Path|str ='tropo_corr',
        flip_sign: bool = False):
    """
    Perform tropospheric noise correction

    Parameters
    ----------
    input_files: Sequence[str]
        List of interferograms (either wrapped or unwrapped)
    nrow: int
        number of rows of the image
    ncol: int
        number of columns of the image
    wvl: float
        Wavelength in meter
    delay_path: Path|str
        Direcotry of tropospheric delay files
    output_path: Path|str
        Directory of corrected interferograms
    flip_sign:bool
        This boolean argument decides how we correct the tropospheric noise
        from original interferograms. By default (flip_sign=False), the
        tropospheric noise should be subtracted. If this does not work, change
        flip_sign to True and try again.

    Notes
    -------
    This function calulates the differential tropospheric delay between the
    secondary date and the reference date of the interferogram, performs the
    tropospheric noise correction.
    """
    os.makedirs(output_path,exist_ok=True)

    logger.info('perform tropospheric noise correction')
    logger.info(f'output interferograms will be saved to {output_path}')
    for ifg_file in tqdm(input_files,desc='tropo correction'):
        basename = os.path.basename(ifg_file)
        date1 = basename[0:8]
        date2 = basename[9:17]
        delay1 = np.fromfile(os.path.join(delay_path,f'{date1}.delay'),
                             dtype=np.float32)
        delay2 = np.fromfile(os.path.join(delay_path,f'{date2}.delay'),
                             dtype=np.float32)
        aps = (delay1-delay2)/wvl*4*np.pi
        aps = np.reshape(aps,(nrow,ncol))
        if basename[-4:] == '.int':
            ifg = sario.readslc(ifg_file,ncol)
            if flip_sign:
                ifgcorr = ifg*np.exp(1j*aps)
            else:
                ifgcorr = ifg*np.exp(-1j*aps)
            output_file = os.path.join(output_path, f'{date1}_{date2}.int')
            sario.saveslc(ifgcorr,output_file)
        else:
            ifg = sario.readc(ifg_file,ncol)
            if flip_sign:
                ifg.imag = ifg.imag+aps
            else:
                ifg.imag = ifg.imag-aps
            output_file = os.path.join(output_path, f'{date1}_{date2}.unw')
            sario.savec(ifg,output_file)

def tropo_proj(
        dem_file: Path|str,
        rsc_file: Path|str,
        look_angle_file: Path|str,
        /,
        tropo_delay_path: Path|str = 'tropo_delay',
        verbose: bool = False):
    """
    Download tropospheric delay data and do projection

    Parameters
    ----------
    dem_file: Path|str
        DEM file
    rsc_file: Path|str
        rsc file
    look_angle_file: Path|str
        Look angle at each radar pixel
    tropo_delay_path: path|str
        Directory to store tropospheric delay product
    verbose: bool
        Show processing message
    """
    os.makedirs(tropo_delay_path, exist_ok = True)
    grb_path = Path(os.path.join(tropo_delay_path, 'grb'))
    if not grb_path.is_dir():
        logger.error('Cannot find the folder containting grb files')
        exit(1)

    # read lat/lon/dem/inc
    logger.info('project tropospheric delay to LOS directions')
    rsc = geocoordinates.GeoCoordinates(rsc_file)
    nrow,ncol = rsc.nlat,rsc.nlon
    lat,lon = rsc.grid()
    dem = np.fromfile(dem_file,dtype=np.int16).reshape(nrow,ncol)
    inc = np.fromfile(look_angle_file,dtype=np.float32).reshape(nrow,ncol)
    grb_files = glob.glob(os.path.join(grb_path,'*.grb'))
    tropo_proj_era5(grb_files,lat,lon,dem,inc,tropo_delay_path,verbose=verbose)

def era5_correction(
        ifg_list: Sequence[str],
        rsc_file: Path|str,
        /,
        delay_path: Path|str = 'tropo',
        output_path: Path|str = 'tropo_corr',
        flip_sign: bool = False):
    """
    Carry out tropospheric noise correction

    Parameters
    ----------
    ifg_list: Sequence[str]
        Input list of interferograms
    rsc_file: Path|str
        rsc file
    delay_path: Path|str
        Direcotry of tropospheric delay files
    output_path: Path|str
        Directory of corrected interferograms
    flip_sign: bool
        This boolean argument decides how we correct the tropospheric noise
        from original interferograms. By default (flip_sign=False), the
        tropospheric noise should be subtracted. If this does not work, change
        flip_sign to True and try again.
    """
    rsc = geocoordinates.GeoCoordinates(rsc_file)
    nrow, ncol = rsc.nlat, rsc.nlon
    # tropospheric noise correction
    _era5_correction(ifg_list, nrow, ncol, delay_path = delay_path,
            output_path = output_path, flip_sign = flip_sign)

def main(ifg_path: str,
         /,
         config: str = 'config.yaml',
         verbose: bool = False):
    """
    Run tropospheric noise correction
    
    Parameters
    ----------
    ifg_path: str
        Interferograms to be corrected
    config: Path|str
        Configuration file
    verbose: bool
        If True, set the logging level to DEBUG
    """
    if verbose:
        set_logging_level(logger, 'DEBUG')
    from s1proc._config import load_config
    icfg,pcfg = load_config(config)

    # determine the acquisition hour
    if pcfg.hour is None:
        zip_list_file = os.path.join(icfg.data_path,'zip_list')
        zip_file = None
        if not os.path.exists(zip_list_file):
            zip_list = glob.glob(os.path.join(icfg.data_path,'*.zip'))
            if len(zip_list) > 0:
                zip_file = zip_list[0]
            with open(zip_list_file, 'w') as f:
                f.write('\n'.join(zip_list))
        else:
            with open(zip_list_file, 'r') as f:
                zip_file = f.readline().strip()
        if zip_file is None or zip_file == '':
            logger.error('Cannot derive the acquisition hour of radar data. ' +
                    'User must specify the hour option in the configuration ' +
                    'file.')
            return
        else:
            sent = sario.sentinel_parser(zip_file)
            start_time = datetime.strptime(sent['start_time'],"%Y%m%dT%H%M%S")
            sdate = datetime.strftime(start_time,"%Y%m%d")
            hour = start_time.hour
    logger.debug(f'Acquisition hour is set to {hour}')

    # parse input data
    raw_ifg_list = get_input_files(ifg_path)
    ifg_list = IfgList(raw_ifg_list)
    date_list = ifg_list.get_date_list()

    # download files for tropospheric noise correction
    tropo_delay_path = icfg.tropo_delay_path
    grb_path = os.path.join(tropo_delay_path, 'grb')
    os.makedirs(grb_path, exist_ok = True)
    logger.info('download files for tropspheric noise correction')
    download_era5(date_list, hour,  grb_path, icfg.rsc_file)

    # Project tropospheric delay to imaging grid
    dem_file = icfg.multilook_dem_file
    rsc_file = icfg.multilook_rsc_file
    geometry_path = icfg.geometry_path
    if not os.path.exists(geometry_path):
        os.makedirs(geometry_path)
    losvec_file = os.path.join(geometry_path, 'los')
    look_angle_file = os.path.join(geometry_path, 'look_angle')
    if not os.path.exists(dem_file) or not os.path.exists(rsc_file):
        multilook_dem(icfg.dem_file, icfg.rsc_file, dem_file, rsc_file,
                pcfg.rowlook, pcfg.collook)
    if not os.path.exists(look_angle_file):
        los(dem_file, rsc_file, icfg.proc_path, losvec_file, look_angle_file)
    tropo_proj(dem_file, rsc_file, look_angle_file, tropo_delay_path, verbose)

    # tropospheric phase correction
    era5_correction(raw_ifg_list, rsc_file, tropo_delay_path,
            icfg.tropo_corr_path, pcfg.flip_sign)
     
    return

